# Generated by Django 2.2 on 2020-05-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawaiApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='drugStore',
        ),
        migrations.AddField(
            model_name='drug',
            name='drugStores',
            field=models.ManyToManyField(to='dawaiApp.drugStore'),
        ),
    ]
