# Generated by Django 2.2 on 2020-05-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawaiApp', '0002_question_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='info',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
