# Generated by Django 2.2 on 2020-05-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dawaiApp', '0003_auto_20200508_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default=' '),
        ),
    ]
